A01V3      20Meet Entries                  Hy-Tek, Ltd               7.0CHy-Tek, Ltd         252-633-517702152014                                    TM41    N21
B11        YMCA STATE CHAMPIONSHIP 2001                                              Brighton, NY USA                   Y0316200103182001            Y       N39
C11NI      NICCRRCarwell County River Racers   River Racers    PO Box 786                                  Owensboro           NY12234     USA               N89
D01NI  7   MUNSON, MARIANNE N          042188MARNMU USA0421198812FF  501 15 1112             NT                                                              N47
D3042188MARNMUNS               X FFFFFFFFFFFFF                                                                                                               N13
D01NI  7   MUNSON, MARIANNE N          042188MARNMU USA0421198812FF 2001 27 1112             NT                                                              N57
D01NI  7   MUNSON, MARIANNE N          042188MARNMU USA0421198812FF 1001 55 1112             NT                                                              N57
D01NI  5   MUNSON, ELIZABETH N         111789ELINMU USA1117198911FF  501 15 1112             NT                                                              N67
D3111789ELINMUNS               S FFFFFFFFFFFFF                                                                                                               N03
D01NI  5   MUNSON, ELIZABETH N         111789ELINMU USA1117198911FF 2001 27 1112             NT                                                              N77
D01NI  5   MUNSON, ELIZABETH N         111789ELINMU USA1117198911FF 1001 55 1112             NT                                                              N77
D01NI  9   Geary, Heather J            101986HEAJGE USA1019198614FF  501 17 1314             NT                                                              N38
D3101986HEAJGEAR               S FFFFFFFFFFFFF                                                                                                               N82
D01NI  9   Geary, Heather J            101986HEAJGE USA1019198614FF 1002 23 1314             NT                                                              N48
D01NI  9   Geary, Heather J            101986HEAJGE USA1019198614FF 1004 63 1314             NT                                                              N48
D01NI  9   Kerr, Julie A               011586JULAKE USA0115198614FF 5001  3 1314             NT                                                              N27
D3011586JULAKERR               S FFFFFFFFFFFFF                                                                                                               N03
D01NI  9   Kerr, Julie A               011586JULAKE USA0115198614FF 2001 29 1314             NT                                                              N47
D01NI  9   Mason, Mandy A              060786MANAMA USA0607198614FF  501 17 1314           29.19Y                                                            N97
D3060786MANAMASO               S FFFFFFFFFFFFF                                                                                                               N92
D01NI  9   Mason, Mandy A              060786MANAMA USA0607198614FF 1002 23 1314         1:16.96Y                                                            N28
D01NI  12  Neal, Lynn J                030484LYNJNE USA0304198416FF  501 19 15OV             NT                                                              N47
D3030484LYNJNEAL               S FFFFFFFFFFFFF                                                                                                               N92
D01NI  12  Neal, Lynn J                030484LYNJNE USA0304198416FF 1001 59 15OV             NT                                                              N57
D01NI  12  Neal, Lynn J                030484LYNJNE USA0304198416FF 1004 65 15OV             NT                                                              N57
D01NI  9   Stilley, Erin J             071786ERIJST USA0717198614FF 5001  3 1314             NT                                                              N48
D3071786ERIJSTIL               S FFFFFFFFFFFFF                                                                                                               N03
D01NI  9   Stilley, Erin J             071786ERIJST USA0717198614FF 2005  9 1314             NT                                                              N48
D01NI  9   Stilley, Erin J             071786ERIJST USA0717198614FF 1003 69 1314             NT                                                              N58
D01NI  8   Skinner, Leanne T           013087LEATSK USA0130198713FF 5001  3 1314             NT                                                              N98
D3013087LEATSKIN               S FFFFFFFFFFFFF                                                                                                               N92
D01NI  8   Skinner, Leanne T           013087LEATSK USA0130198713FF 2001 29 1314             NT                                                              N09
D01NI  8   Skinner, Leanne T           013087LEATSK USA0130198713FF 1001 57 1314             NT                                                              N09
D01NI  8   Younce, Jarrett L           100386JARLYO USA1003198614MM 5001  4 1314             NT                                                              N29
D3100386JARLYOUN               X FFFFFFFFFFFFF                                                                                                               N13
D01NI  8   Younce, Jarrett L           100386JARLYO USA1003198614MM 2001 30 1314             NT                                                              N29
D01NI  8   Younce, Jarrett L           100386JARLYO USA1003198614MM 1001 58 1314           55.60Y                                                            N59
D01NI  11  Zaytoun, Chance J           082983CHAJZA USA0829198317MM 2005 12 15OV         2:12.05Y                                                            N00
D3082983CHAJZAYT               X FFFFFFFFFFFFF                                                                                                               N03
D01NI  11  Zaytoun, Chance J           082983CHAJZA USA0829198317MM 2001 32 15OV         1:52.91Y                                                            N00
D01NI  11  Zaytoun, Chance J           082983CHAJZA USA0829198317MM 1001 60 15OV           52.12Y                                                            N79
D01NI  5   Mansfield, Brandy M         111389BRAMMA USA1113198911FF 1001 45 0910             NT                                                              N69
D3111389BRAMMANS               S FFFFFFFFFFFFF                                                                                                               N92
D01NI  5   Mansfield, Brandy M         111389BRAMMA USA1113198911FF  502 49 0910             NT                                                              N59
D01NI  5   Mansfield, Brandy M         111389BRAMMA USA1113198911FF  501 81 0910             NT                                                              N59
D01NI  9   Allen, Samantha C           052186SAMCAL USA0521198614FF 5001  3 1314             NT                                                              N68
D3052186SAMCALLESam            S FFFFFFFFFFFFF                                                                                                               N83
D01NI  9   Allen, Samantha C           052186SAMCAL USA0521198614FF  501 17 1314             NT                                                              N68
D01NI  9   Allen, Samantha C           052186SAMCAL USA0521198614FF 2001 29 1314             NT                                                              N78
D01NI  5   Fields, Grace J             100690GRAJFI USA1006199010FF 1001 45 0910             NT                                                              N87
D3100690GRAJFIELGracie         S FFFFFFFFFFFFF                                                                                                               N94
D01NI  5   Fields, Grace J             100690GRAJFI USA1006199010FF  501 81 0910             NT                                                              N87
D01NI  5   Fields, Grace J             100690GRAJFI USA1006199010FF  504 85 0910             NT                                                              N87
D01NI  4   Kruger, Matthew R           032691MATRKR USA032619919 MM  502 50 0910             NT                                                              N19
D3032691MATRKRUGMATT           S FFFFFFFFFFFFF                                                                                                               N04
D01NI  11  Linson, Tabitha L           073084TABLLI USA0730198416FF 5001  1 15OV             NT                                                              N29
D3073084TABLLINSTabi           S FFFFFFFFFFFFF                                                                                                               N34
D01NI  11  Linson, Tabitha L           073084TABLLI USA0730198416FF 2001 31 15OV             NT                                                              N39
D01NI  11  Linson, Tabitha L           073084TABLLI USA0730198416FF 1004 65 15OV             NT                                                              N49
D01NI  9   Lamm, Rhonda L              031586RHOLLA USA0315198614FF  501 17 1314             NT                                                              N77
D3031586RHOLLAMM               S FFFFFFFFFFFFF                                                                                                               N92
D01NI  9   Lamm, Rhonda L              031586RHOLLA USA0315198614FF 2001 29 1314             NT                                                              N87
D01NI  9   Lamm, Rhonda L              031586RHOLLA USA0315198614FF 1004 63 1314             NT                                                              N87
D01NI  9   Orbison, Robert A           010286ROBAOR USA0102198614MM  501 18 1314             NT                                                              N09
D3010286ROBAORBIBobby          S FFFFFFFFFFFFF                                                                                                               N64
D01NI  9   Orbison, Robert A           010286ROBAOR USA0102198614MM 1002 24 1314             NT                                                              N19
D01NI  9   Orbison, Robert A           010286ROBAOR USA0102198614MM 1001 58 1314             NT                                                              N19
D01NI  4   Edgerton, Sharon L          061091SHALED USA061019919 FF  501 81 0910           35.38Y                                                            N49
D3061091SHALEDGE               S FFFFFFFFFFFFF                                                                                                               N72
D01NI  4   Edgerton, Sharon L          061091SHALED USA061019919 FF  503 89 0910             NT                                                              N29
D01NI  4   Respess, Sherry T           021591SHETRE USA021519919 FF 1001 45 0910         1:22.45Y                                                            N79
D3021591SHETRESP               S FFFFFFFFFFFFF                                                                                                               N03
D01NI  4   Respess, Sherry T           021591SHETRE USA021519919 FF  501 81 0910           35.37Y                                                            N49
D01NI  4   Respess, Sherry T           021591SHETRE USA021519919 FF  503 89 0910           45.46Y                                                            N59
D01NI  9   Hale, Sandra L              081186SANLHA USA0811198614FF 5001  3 1314             NT                                                              N57
D3081186SANLHALE               S FFFFFFFFFFFFF                                                                                                               N82
D01NI  9   Hale, Sandra L              081186SANLHA USA0811198614FF 1002 23 1314             NT                                                              N67
D01NI  9   Hale, Sandra L              081186SANLHA USA0811198614FF 2001 29 1314             NT                                                              N67
D01NI  12  Denver, Emily L             112982EMILDE USA1129198218FF 5001  1 15OV             NT                                                              N58
D3112982EMILDENV               S FFFFFFFFFFFFF                                                                                                               N92
D01NI  12  Fesperman, Daniel L         012184DANLFE USA0121198416MM 5001  2 15OV         4:51.00Y                                                            N30
D3012184DANLFESPDanny          S FFFFFFFFFFFFF                                                                                                               N64
D01NI  12  Fesperman, Daniel L         012184DANLFE USA0121198416MM 2001 32 15OV         1:45.50Y                                                            N40
D01NI  12  Fesperman, Daniel L         012184DANLFE USA0121198416MM 1004 66 15OV           52.99Y                                                            N30
D01NI  6   Landau, Candice L           101988CANLLA USA1019198812FF  502 21 1112             NT                                                              N58
D3101988CANLLANDCandy          S FFFFFFFFFFFFF                                                                                                               N64
D01NI  6   Landau, Candice L           101988CANLLA USA1019198812FF 1001 55 1112             NT                                                              N68
D01NI  6   Landau, Candice L           101988CANLLA USA1019198812FF  503 67 1112             NT                                                              N68
D01NI  5   Landau, Stevie G            062790STEGLA USA0627199010MM 1005 42 0910             NT                                                              N68
D3062790STEGLAND               S FFFFFFFFFFFFF                                                                                                               N92
D01NI  5   Landau, Stevie G            062790STEGLA USA0627199010MM  501 82 0910             NT                                                              N58
D01NI  5   Landau, Stevie G            062790STEGLA USA0627199010MM  504 86 0910           41.05Y                                                            N88
D01NI  4   Kruger, Jedia M             021691JEDMKR USA021619919 MM  501 82 0910           35.39Y                                                            N38
D3021691JEDMKRUGJed            S FFFFFFFFFFFFF                                                                                                               N83
D01NI  5   Montrose, Marilyn L         041090MARLMO USA0410199010FF 1001 45 0910             NT                                                              N99
D3041090MARLMONT               S FFFFFFFFFFFFF                                                                                                               N03
D01NI  5   Montrose, Marilyn L         041090MARLMO USA0410199010FF  504 85 0910             NT                                                              N99
D01NI  5   Montrose, Marilyn L         041090MARLMO USA0410199010FF 2001103 0910             NT                                                              N00
D01NI  9   Windham, Donna L            080386DONLWI USA0803198614FF  501 17 1314           29.17Y                                                            N88
D3080386DONLWIND               S FFFFFFFFFFFFF                                                                                                               N03
D01NI  9   Windham, Donna L            080386DONLWI USA0803198614FF 1002 23 1314         1:16.29Y                                                            N19
D01NI  9   Brown, Jessica S            101885JESSBR USA1018198515FF  501 19 15OV           29.19Y                                                            N39
D3101885JESSBROWJessi          X FFFFFFFFFFFFF                                                                                                               N94
D01NI  9   Brown, Jessica S            101885JESSBR USA1018198515FF 1002 25 15OV         1:15.57Y                                                            N69
D01NI  9   Renn, Trina K               020286TRIKRE USA0202198614FF  501 17 1314           29.95Y                                                            N87
D3020286TRIKRENN               S FFFFFFFFFFFFF                                                                                                               N03
D01NI  9   Renn, Trina K               020286TRIKRE USA0202198614FF 1002 23 1314         1:16.90Y                                                            N08
D01NI  11  Truluck, Tina A             081584TINATR USA0815198416FF  501 19 15OV             NT                                                              N78
D3081584TINATRUL               S FFFFFFFFFFFFF                                                                                                               N13
D01NI  11  Truluck, Tina A             081584TINATR USA0815198416FF 1003 71 15OV             NT                                                              N88
D01NI  10  Asorphi, Mary C             073185MARCAS USA0731198515FF  501 19 15OV             NT                                                              N58
D3073185MARCASORMary           S FFFFFFFFFFFFF                                                                                                               N44
D01NI  10  Asorphi, Mary C             073185MARCAS USA0731198515FF 1001 59 15OV             NT                                                              N68
D01NI  10  Bradley, Tucker D           032889TUCDBR USA0328198911FF 1003 71 15OV             NT                                                              N49
D3032889TUCDBRADTucker         S FFFFFFFFFFFFF                                                                                                               N15
D01NI  5   Branton, Daniel W           101089DANWBR USA1010198911MM 1001 56 1112         1:08.87Y                                                            N59
D3101089DANWBRANDan            S FFFFFFFFFFFFF                                                                                                               N83
D01NI  5   Branton, Daniel W           101089DANWBR USA1010198911MM  503 68 1112           39.96Y                                                            N29
D01NI  4   Tolson, Gina L              071591KATRTU USA071519919 FF  502 49 0910           41.90Y                                                            N28
D3071591KATRTUCK               S FFFFFFFFFFFFF                                                                                                               N03
D01NI  4   Tolson, Gina L              071591KATRTU USA071519919 FF  501 81 0910           35.38Y                                                            N28
D01NI  8   Tull, Marissa C             081187MARCTU USA0811198713FF  501 17 1314           29.18Y                                                            N68
D3081187MARCTULL               S FFFFFFFFFFFFF                                                                                                               N03
D01NI  8   Tull, Marissa C             081187MARCTU USA0811198713FF 1002 23 1314         1:16.98Y                                                            N98
D01NI  8   Tull, Marissa C             081187MARCTU USA0811198713FF 1001 57 1314         1:03.59Y                                                            N98
D01NI  11  MURPHY, ABIGAIL J           050684ABIJMU USA0506198416FF 2005 11 15OV             NT                                                              N57
D3050684ABIJMURP               S FFFFFFFFFFFFF                                                                                                               N92
D01NI  11  MURPHY, ABIGAIL J           050684ABIJMU USA0506198416FF 2001 31 15OV             NT                                                              N47
D01NI  11  MURPHY, ABIGAIL J           050684ABIJMU USA0506198416FF 1003 71 15OV             NT                                                              N57
D01NI  2   Respess, Ashlynn M          032593ASHMRE USA032519937 FF  501 43 UN08           44.48Y                                                            N00
D3032593ASHMRESP               S FFFFFFFFFFFFF                                                                                                               N03
D01NI  2   Respess, Ashlynn M          032593ASHMRE USA032519937 FF  251 79 UN08           19.53Y                                                            N10
D01NI  2   Respess, Ashlynn M          032593ASHMRE USA032519937 FF  253 87 UN08             NT                                                              N89
D01NI  6   Snyder, Tabitha B           020189TABBSN USA0201198911FF  501 15 1112           30.79Y                                                            N09
D3020189TABBSNYDTabi           S FFFFFFFFFFFFF                                                                                                               N24
D01NI  6   Snyder, Tabitha B           020189TABBSN USA0201198911FF  502 21 1112           36.57Y                                                            N09
D01NI  6   Stanton, Shannah L          012289SHALST USA0122198911FF  503 67 1112             NT                                                              N49
D3012289SHALSTAN               S FFFFFFFFFFFFF                                                                                                               N92
D01NI  10  Tripplet, Anna K            090886ANNKTR USA0908198614FF  501 19 15OV             NT                                                              N19
D3090886ANNKTRIP               S FFFFFFFFFFFFF                                                                                                               N03
D01NI  10  Tripplet, Anna K            090886ANNKTR USA0908198614FF 1002 25 15OV             NT                                                              N29
D01NI  10  Tripplet, Anna K            090886ANNKTR USA0908198614FF 1001 59 15OV             NT                                                              N29
D01NI  12  Brown, Katie L              072183KATLBR USA0721198317FF  501 19 15OV             NT                                                              N28
D3072183KATLBROW               S FFFFFFFFFFFFF                                                                                                               N03
D01NI  12  Brown, Katie L              072183KATLBR USA0721198317FF 1001 59 15OV             NT                                                              N28
D01NI  12  Brown, Katie L              072183KATLBR USA0721198317FF 1004 65 15OV             NT                                                              N28
D01NI  2   Stanton, Gwendolyn E        041193GWEEST USA041119937 FF  252 47 UN08           22.68Y                                                            N90
D3041193GWEESTANGwen           S FFFFFFFFFFFFF                                                                                                               N44
D01NI  7   Guion, Bethany G            091088BETGGU USA0910198812FF  501 15 1112             NT                                                              N58
D3091088BETGGUIO               S FFFFFFFFFFFFF                                                                                                               N92
D01NI  7   Guion, Bethany G            091088BETGGU USA0910198812FF  502 21 1112             NT                                                              N58
D01NI  7   Guion, Bethany G            091088BETGGU USA0910198812FF  504 61 1112             NT                                                              N58
D01NI  9   Bays, Lori L                100285LORLBA USA1002198515FF 2005 11 15OV             NT                                                              N37
D3100285LORLBAYSLori           S FFFFFFFFFFFFF                                                                                                               N44
D01NI  9   Bays, Lori L                100285LORLBA USA1002198515FF 1002 25 15OV           58.40Y                                                            N67
D01NI  9   Bays, Lori L                100285LORLBA USA1002198515FF 1004 65 15OV             NT                                                              N37
D01NI  2   Edgerton, Shanna J          042493SHAJED USA042419937 FF  252 47 UN08           22.48Y                                                            N79
D3042493SHAJEDGE               S FFFFFFFFFFFFF                                                                                                               N82
D01NI  8   Hauserman, Lynne A          012487LYNAHA USA0124198713FF  501 17 1314           29.19Y                                                            N69
D3012487LYNAHAUS               X FFFFFFFFFFFFF                                                                                                               N03
D01NI  10  Chesson, Christine C        101184CHRCCH USA1011198416FF  501 19 15OV             NT                                                              N30
D3101184CHRCCHESChris          S FFFFFFFFFFFFF                                                                                                               N64
D01NI  10  Chesson, Christine C        101184CHRCCH USA1011198416FF 1002 25 15OV             NT                                                              N40
D01NI  10  Chesson, Christine C        101184CHRCCH USA1011198416FF 1001 59 15OV             NT                                                              N40
D01NI  9   Santos, Justine N           020986JUSNSA USA0209198614FF  501 17 1314           29.91Y                                                            N69
D3020986JUSNSANT               X FFFFFFFFFFFFF                                                                                                               N13
D01NI  9   Santos, Justine N           020986JUSNSA USA0209198614FF 1001 57 1314         1:03.59Y                                                            N99
D01NI  9   Simpson, Devon S            020686DEVSSI USA0206198614FF  501 17 1314             NT                                                              N88
D3020686DEVSSIMP               X FFFFFFFFFFFFF                                                                                                               N03
D01NI  9   Simpson, Devon S            020686DEVSSI USA0206198614FF 2001 29 1314             NT                                                              N98
D01NI  9   Simpson, Devon S            020686DEVSSI USA0206198614FF 1001 57 1314         1:03.55Y                                                            N49
D01NI  6   Conner, Heather D           091788HEADCO USA0917198812FF  501 15 1112           30.75Y                                                            N09
D3091788HEADCONN               S FFFFFFFFFFFFF                                                                                                               N82
D01NI  6   Conner, Heather D           091788HEADCO USA0917198812FF 1001 55 1112         1:08.96Y                                                            N39
D01NI  5   Mallard, Patrick J          102089PATJMA USA1020198911MM  502 50 0910             NT                                                              N29
D3102089PATJMALL               S FFFFFFFFFFFFF                                                                                                               N92
D01NI  5   Mallard, Patrick J          102089PATJMA USA1020198911MM  504 86 0910             NT                                                              N29
D01NI  5   Mallard, Patrick J          102089PATJMA USA1020198911MM 2001104 0910             NT                                                              N39
E01NI      ANICCRR  F 2007 33 1112   03162001 2:13.53Y                                                                                                       N62
F01NI       33 NICCRRAMUNSON, MARIANNE N          042188MARNMUUSA0421198812F000             042188MARNMUNS                                                   N30
F01NI       33 NICCRRALandau, Candice L           101988CANLLAUSA1019198812F000             101988CANLLANDCandy                                              N92
F01NI       33 NICCRRAGuion, Bethany G            091088BETGGUUSA0910198812F000             091088BETGGUIO                                                   N21
F01NI       33 NICCRRAMUNSON, ELIZABETH N         111789ELINMUUSA1117198911F000             111789ELINMUNS                                                   N50
F01NI       33 NICCRRAConner, Heather D           091788HEADCOUSA0917198812F000             091788HEADCONN                                                   N41
F01NI       33 NICCRRASnyder, Tabitha B           020189TABBSNUSA0201198912F000             020189TABBSNYDTabi                                               N82
F01NI       33 NICCRRAStanton, Shannah L          012289SHALSTUSA0122198912F000             012289SHALSTAN                                                   N22
E01NI      ANICCRR  F 2007 35 1314   03162001 2:08.96Y                                                                                                       N72
F01NI       35 NICCRRAHale, Sandra L              081186SANLHAUSA0811198614F000             081186SANLHALE                                                   N20
F01NI       35 NICCRRAStilley, Erin J             071786ERIJSTUSA0717198614F000             071786ERIJSTIL                                                   N21
F01NI       35 NICCRRAGeary, Heather J            101986HEAJGEUSA1019198614F000             101986HEAJGEAR                                                   N90
F01NI       35 NICCRRAAllen, Samantha C           052186SAMCALUSA0521198614F000             052186SAMCALLESam                                                N32
F01NI       35 NICCRRALamm, Rhonda L              031586RHOLLAUSA0315198615F000             031586RHOLLAMM                                                   N40
F01NI       35 NICCRRASimpson, Devon S            020686DEVSSIUSA0206198615F000             020686DEVSSIMP                                                   N61
F01NI       35 NICCRRAKerr, Julie A               011586JULAKEUSA0115198615F000             011586JULAKERR                                                   N00
F01NI       35 NICCRRAMason, Mandy A              060786MANAMAUSA0607198614F000             060786MANAMASO                                                   N30
E01NI      ANICCRR  F 2007 37 15OV   03162001 1:54.59Y                                                                                                       N03
F01NI       37 NICCRRABays, Lori L                100285LORLBAUSA1002198515F000             100285LORLBAYSLori                                               N11
F01NI       37 NICCRRATruluck, Tina A             081584TINATRUSA0815198416F000             081584TINATRUL                                                   N21
F01NI       37 NICCRRABrown, Katie L              072183KATLBRUSA0721198317F000             072183KATLBROW                                                   N50
F01NI       37 NICCRRADenver, Emily L             112982EMILDEUSA1129198218F000             112982EMILDENV                                                   N80
F01NI       37 NICCRRATripplet, Anna K            090886ANNKTRUSA0908198614F000             090886ANNKTRIP                                                   N61
F01NI       37 NICCRRAMURPHY, ABIGAIL J           050684ABIJMUUSA0506198416F000             050684ABIJMURP                                                   N79
F01NI       37 NICCRRANeal, Lynn J                030484LYNJNEUSA0304198417F000             030484LYNJNEAL                                                   N79
F01NI       37 NICCRRALinson, Tabitha L           073084TABLLIUSA0730198416F000             073084TABLLINSTabi                                               N92
E01NI      ANICCRR  F 2007 53 0910   03162001 2:36.70Y                                                                                                       N62
F01NI       53 NICCRRAMansfield, Brandy M         111389BRAMMAUSA1113198911F000             111389BRAMMANS                                                   N22
F01NI       53 NICCRRAEdgerton, Sharon L          061091SHALEDUSA06101991 9F000             061091SHALEDGE                                                   N71
F01NI       53 NICCRRAMontrose, Marilyn L         041090MARLMOUSA0410199010F000             041090MARLMONT                                                   N62
F01NI       53 NICCRRAFields, Grace J             100690GRAJFIUSA1006199010F000             100690GRAJFIELGracie                                             N42
F01NI       53 NICCRRARespess, Sherry T           021591SHETREUSA0215199110F000             021591SHETRESP                                                   N02
F01NI       53 NICCRRATolson, Gina L              071591KATRTUUSA07151991 9F000             071591KATRTUCK                                                   N70
F01NI       53 NICCRRADawson, Sara J              020390SARJDAUSA0203199011F000             020390SARJDAWS                                                   N30
E01NI      ANICCRR  M 2007 54 0910   03162001 2:43.27Y                                                                                                       N72
F01NI       54 NICCRRAKruger, Matthew R           032691MATRKRUSA03261991 9M000             032691MATRKRUGMATT                                               N92
F01NI       54 NICCRRALandau, Stevie G            062790STEGLAUSA0627199010M000             062790STEGLAND                                                   N21
F01NI       54 NICCRRAMallard, Patrick J          102089PATJMAUSA1020198911M000             102089PATJMALL                                                   N91
F01NI       54 NICCRRAKruger, Jedia M             021691JEDMKRUSA0216199110M000             021691JEDMKRUGJed                                                N71
E01NI      ANICCRR  F 2006 73 1112   03162001 1:56.34Y                                                                                                       N62
F01NI       73 NICCRRAGuion, Bethany G            091088BETGGUUSA0910198812F000             091088BETGGUIO                                                   N31
F01NI       73 NICCRRAMUNSON, MARIANNE N          042188MARNMUUSA0421198812F000             042188MARNMUNS                                                   N30
F01NI       73 NICCRRAMUNSON, ELIZABETH N         111789ELINMUUSA1117198911F000             111789ELINMUNS                                                   N50
F01NI       73 NICCRRALandau, Candice L           101988CANLLAUSA1019198812F000             101988CANLLANDCandy                                              N92
F01NI       73 NICCRRAConner, Heather D           091788HEADCOUSA0917198812F000             091788HEADCONN                                                   N41
F01NI       73 NICCRRASnyder, Tabitha B           020189TABBSNUSA0201198912F000             020189TABBSNYDTabi                                               N82
F01NI       73 NICCRRAStanton, Shannah L          012289SHALSTUSA0122198912F000             012289SHALSTAN                                                   N22
E01NI      ANICCRR  F 2006 75 1314   03162001 1:49.46Y                                                                                                       N72
F01NI       75 NICCRRAAllen, Samantha C           052186SAMCALUSA0521198614F000             052186SAMCALLESam                                                N32
F01NI       75 NICCRRASkinner, Leanne T           013087LEATSKUSA0130198714F000             013087LEATSKIN                                                   N61
F01NI       75 NICCRRAHale, Sandra L              081186SANLHAUSA0811198614F000             081186SANLHALE                                                   N20
F01NI       75 NICCRRALamm, Rhonda L              031586RHOLLAUSA0315198615F000             031586RHOLLAMM                                                   N40
F01NI       75 NICCRRASimpson, Devon S            020686DEVSSIUSA0206198615F000             020686DEVSSIMP                                                   N61
F01NI       75 NICCRRAStilley, Erin J             071786ERIJSTUSA0717198614F000             071786ERIJSTIL                                                   N21
F01NI       75 NICCRRAGeary, Heather J            101986HEAJGEUSA1019198614F000             101986HEAJGEAR                                                   N90
F01NI       75 NICCRRAKerr, Julie A               011586JULAKEUSA0115198615F000             011586JULAKERR                                                   N00
E01NI      ANICCRR  F 4006 77 15OV   03162001 3:41.11Y                                                                                                       N03
F01NI       77 NICCRRABrown, Katie L              072183KATLBRUSA0721198317F000             072183KATLBROW                                                   N60
F01NI       77 NICCRRADenver, Emily L             112982EMILDEUSA1129198218F000             112982EMILDENV                                                   N80
F01NI       77 NICCRRABays, Lori L                100285LORLBAUSA1002198515F000             100285LORLBAYSLori                                               N21
F01NI       77 NICCRRAMURPHY, ABIGAIL J           050684ABIJMUUSA0506198416F000             050684ABIJMURP                                                   N89
F01NI       77 NICCRRANeal, Lynn J                030484LYNJNEUSA0304198417F000             030484LYNJNEAL                                                   N89
F01NI       77 NICCRRALinson, Tabitha L           073084TABLLIUSA0730198416F000             073084TABLLINSTabi                                               N03
F01NI       77 NICCRRATripplet, Anna K            090886ANNKTRUSA0908198614F000             090886ANNKTRIP                                                   N61
F01NI       77 NICCRRAChesson, Christine C        101184CHRCCHUSA1011198416F000             101184CHRCCHESChris                                              N34
E01NI      ANICCRR  F 2006 93 0910   03162001 2:17.88Y                                                                                                       N72
F01NI       93 NICCRRAMontrose, Marilyn L         041090MARLMOUSA0410199010F000             041090MARLMONT                                                   N62
F01NI       93 NICCRRAMansfield, Brandy M         111389BRAMMAUSA1113198911F000             111389BRAMMANS                                                   N22
F01NI       93 NICCRRAFields, Grace J             100690GRAJFIUSA1006199010F000             100690GRAJFIELGracie                                             N42
F01NI       93 NICCRRARespess, Sherry T           021591SHETREUSA0215199110F000             021591SHETRESP                                                   N02
F01NI       93 NICCRRADawson, Sara J              020390SARJDAUSA0203199011F000             020390SARJDAWS                                                   N30
F01NI       93 NICCRRAEdgerton, Sharon L          061091SHALEDUSA06101991 9F000             061091SHALEDGE                                                   N71
F01NI       93 NICCRRATolson, Gina L              071591KATRTUUSA07151991 9F000             071591KATRTUCK                                                   N70
E01NI      ANICCRR  M 2006 94 0910   03162001 2:18.22Y                                                                                                       N72
F01NI       94 NICCRRAMallard, Patrick J          102089PATJMAUSA1020198911M000             102089PATJMALL                                                   N91
F01NI       94 NICCRRALandau, Stevie G            062790STEGLAUSA0627199010M000             062790STEGLAND                                                   N21
F01NI       94 NICCRRAKruger, Matthew R           032691MATRKRUSA03261991 9M000             032691MATRKRUGMATT                                               N92
F01NI       94 NICCRRAKruger, Jedia M             021691JEDMKRUSA0216199110M000             021691JEDMKRUGJed                                                N71
E01NI      ANICCRR  F 2006  5 UNOV   03162001 1:41.51Y                                                                                                       N23
F01NI        5 NICCRRABrown, Katie L              072183KATLBRUSA0721198317F000             072183KATLBROW                                                   N40
F01NI        5 NICCRRADenver, Emily L             112982EMILDEUSA1129198218F000             112982EMILDENV                                                   N70
F01NI        5 NICCRRANeal, Lynn J                030484LYNJNEUSA0304198417F000             030484LYNJNEAL                                                   N69
F01NI        5 NICCRRAMURPHY, ABIGAIL J           050684ABIJMUUSA0506198416F000             050684ABIJMURP                                                   N69
F01NI        5 NICCRRABays, Lori L                100285LORLBAUSA1002198515F000             100285LORLBAYSLori                                               N01
F01NI        5 NICCRRAChesson, Christine C        101184CHRCCHUSA1011198416F000             101184CHRCCHESChris                                              N24
F01NI        5 NICCRRAHale, Sandra L              081186SANLHAUSA0811198614F000             081186SANLHALE                                                   N10
F01NI        5 NICCRRASkinner, Leanne T           013087LEATSKUSA0130198714F000             013087LEATSKIN                                                   N51
E01NI      ANICCRR  M 2006  6 UNOV   03162001 1:38.43Y                                                                                                       N23
F01NI        6 NICCRRAFesperman, Daniel L         012184DANLFEUSA0121198417M000             012184DANLFESPDanny                                              N83
F01NI        6 NICCRRAZaytoun, Chance J           082983CHAJZAUSA0829198317M000             082983CHAJZAYT                                                   N71
F01NI        6 NICCRRAYounce, Jarrett L           100386JARLYOUSA1003198614M000             100386JARLYOUN                                                   N91
F01NI        6 NICCRRAOrbison, Robert A           010286ROBAORUSA0102198615M000             010286ROBAORBIBobby                                              N33
E01NI      ANICCRR  F 2007 13 UNOV   03162001 1:59.34Y                                                                                                       N33
F01NI       13 NICCRRATripplet, Anna K            090886ANNKTRUSA0908198614F000             090886ANNKTRIP                                                   N51
F01NI       13 NICCRRAMURPHY, ABIGAIL J           050684ABIJMUUSA0506198416F000             050684ABIJMURP                                                   N79
F01NI       13 NICCRRANeal, Lynn J                030484LYNJNEUSA0304198417F000             030484LYNJNEAL                                                   N79
F01NI       13 NICCRRAChesson, Christine C        101184CHRCCHUSA1011198416F000             101184CHRCCHESChris                                              N34
F01NI       13 NICCRRAAsorphi, Mary C             073185MARCASUSA0731198515F000             073185MARCASORMary                                               N32
F01NI       13 NICCRRALinson, Tabitha L           073084TABLLIUSA0730198416F000             073084TABLLINSTabi                                               N92
F01NI       13 NICCRRAHale, Sandra L              081186SANLHAUSA0811198614F000             081186SANLHALE                                                   N10
F01NI       13 NICCRRAStilley, Erin J             071786ERIJSTUSA0717198614F000             071786ERIJSTIL                                                   N21
E01NI      ANICCRR  M 2007 14 UNOV   03162001 1:57.51Y                                                                                                       N33
F01NI       14 NICCRRAZaytoun, Chance J           082983CHAJZAUSA0829198317M000             082983CHAJZAYT                                                   N81
F01NI       14 NICCRRAYounce, Jarrett L           100386JARLYOUSA1003198614M000             100386JARLYOUN                                                   N02
F01NI       14 NICCRRAFesperman, Daniel L         012184DANLFEUSA0121198417M000             012184DANLFESPDanny                                              N93
F01NI       14 NICCRRAOrbison, Robert A           010286ROBAORUSA0102198615M000             010286ROBAORBIBobby                                              N43
Z01        02Successful Build on 02-15-2014  1  1   1   1   124    51   14    92     0                                                                       N76
